### PR TITLE
ota: Reimplement zip signing ourselves more efficiently

### PR DESCRIPTION
**Pull request by chenxiaolong**
This PR reimplements the majority of the OTA signing process ourselves. In doing so, the patching/signing process is now single-pass and does not require writing temporary zips multiple (6+) times. On my machine, the patching time is consistently ~43% of what it was before.

`ota_utils` is still used for generating `metadata`/`metadata.pb`, but not for any signing. `signapk` has been completely removed, so Java is no longer a dependency. A side effect is avbroot can now run on Alpine Linux or any other non-glibc Linux distribution (signapk depended on the conscrypt native library, which only had glibc builds).

There are also a couple of commits that improve the bit-for-bit reproducibility of the output zip:

* In `payload.bin` -> `vendor_boot.img` -> ramdisk -> `system/etc/security/otacerts.zip`, the certificate filename is now hardcoded to `ota.x509.pem` instead of the previous `<OTA cert filename>/ota.x509.pem`.
* The `metadata.pb` file will no longer differ between two runs with the same input. Previously, the order of some fields within the file depended on how things were ordered in memory.

### CODE REVIEW

**Comment by chenxiaolong** [comment]
Successfully patched and flashed `cheetah-ota-tq1a.230105.002-0c8fdd0d.zip` on my device.

**Comment by chenxiaolong** [comment]
@pascallj I think this should help a decent bit in your setup. This is probably the least disk/memory usage we can achieve during `.zip` signing without reimplementing more AOSP components.

**Comment by pascallj** [comment]
You're putting a lot of work in this project even though you "only intend to maintain the minimum amount of code needed for it to work on my devices" :smiley:. Very welcome though :+1: 

Unfortunately it doesn't make a difference. This run was at 247.2 seconds compared to 240.5 second the last time. It doesn't respect the TMPDIR environment variable, so when using a ramdisk for only the first part of the process I am at 209.9 seconds, but the majority of the IO is indeed in the signing step. Even refreshing the directory listing locks up.

When I put all the files, both input and output on the ramdisk I get a result of 97.0 seconds. Are there a lot of small read/write requests? My hard drive isn't that slow actually (in the order of 100 MB/s sequential).

Also it does produce a different file compared to the previous method. Is that expected?

**Comment by chenxiaolong** [comment]
> You're putting a lot of work in this project even though you "only intend to maintain the minimum amount of code needed for it to work on my devices" smiley. Very welcome though +1

I'm finding this fun :smile:  Slow software annoys me.

> Unfortunately it doesn't make a difference. This run was at 247.2 seconds compared to 240.5 second the last time. It doesn't respect the TMPDIR environment variable, so when using a ramdisk for only the first part of the process I am at 209.9 seconds, but the majority of the IO is indeed in the signing step. Even refreshing the directory listing locks up.
>
> When I put all the files, both input and output on the ramdisk I get a result of 97.0 seconds. Are there a lot of small read/write requests? My hard drive isn't that slow actually (in the order of 100 MB/s sequential).

That's interesting. I would've expected it to make a bit of difference (about 10% reduction in my case). But now that I think about it, the steps that were combined/eliminated were mostly sequential file copies.

Would you mind giving the `zip_signing_timing` branch a try? It's the same as this branch, but with some additional output for the timing of each step of the signing process. I bet the `signapk` step is the slowest.

Mine looks something like this:

```
***** Signing OTA zip *****
Signing attempt 0
- Compute placeholder property files: 0.0s
- Replace metadata files in zip: 3.3s
- Sign zip with signapk: 12.0s
- Compute final property files: 0.0s
Signing attempt 1
- Compute placeholder property files: 0.0s
- Replace metadata files in zip: 3.3s
- Sign zip with signapk: 12.0s
- Compute final property files: 0.0s
- Validate file offsets and sizes: 0.0s
***** Completed after 58.0s *****
```

> Also it does produce a different file compared to the previous method. Is that expected?
>
> EDIT: The difference is not just in the ordering of the files in the zip, but all these files have different checksums:
>
> ```
> META-INF/com/android/otacert
> META-INF/com/android/metadata.pb
> META-INF/com/android/metadata
> payload.bin
> payload_properties.txt
> ```

Nice catch! Long answer incoming :slightly_smiling_face: 

* `payload.bin`: This is different because of the OTA signing certificate's filename. The master branch used to copy the certificate to a temp directory and name it `ota.x509.pem`. The file naming was a requirement for AOSP's signing implementation, but not for our own. This branch uses the specified certificate file directly with no copying.

  Due to a dumb bug in avbroot, the certificate is stored in:

  `payload.bin` -> `vendor_boot.img` -> ramdisk -> `system/etc/security/otacerts.zip` -> `<filename>/ota.x509.pem`

  If your certificate is named like I have it in the README, then the filename inside `otacerts.zip` changed from `ota.x509.pem/ota.x509.pem` to `ota.crt/ota.x509.pem`.

  I've fixed this in this branch in commit 1057c2c5fcb3d2f5877961443669f39c08179153 by hardcoding the filename within `otacerts.zip` to `ota.x509.pem`. Future `payload.bin` outputs will be bit-for-bit reproducible regardless of input filenames.

* `payload_properties.txt`: This changed because the checksum of `payload.bin` changed.

* `META-INF/com/android/metadata` and `.pb`: These files (same content, different encoding) contain the file offset and file size for entries in the zip. They changed for 2 reasons:

  1. In the `payload.bin:<offset>:<size>` field, the size subfield changed because `payload.bin`'s size changed.
  2. If you `diff` the plain-text `metadata` file and open it in an editor that shows trailing whitespace, you should see something like this:

      image

      Due to some implementation details in the signing process, the amount of trailing whitespace changes based on the file order in temporary intermediate `.zip`s during signing. This branch combined some intermediate steps into one, which changed the file order.

      In the final output `.zip`, `metadata`/`metadata.pb` come before every other file. Since they have a different amount of trailing whitespace now, the offsets of every other file changed by a few bytes.

* `META-INF/com/android/otacert`: I'm not sure why this would've changed. It should be an exact copy of your OTA signing certificate. Could you run it through `diff`?

**Comment by pascallj** [comment]
> Would you mind giving the `zip_signing_timing` branch a try? It's the same as this branch, but with some additional output for the timing of each step of the signing process. I bet the `signapk` step is the slowest.

```
***** Signing OTA zip *****
Signing attempt 0
- Compute placeholder property files: 0.0s
- Replace metadata files in zip: 43.7s
- Sign zip with signapk: 40.7s
- Compute final property files: 0.0s
Signing attempt 1
- Compute placeholder property files: 0.0s
- Replace metadata files in zip: 34.0s
- Sign zip with signapk: 33.2s
- Compute final property files: 0.0s
- Validate file offsets and sizes: 0.0s
***** Completed after 240.6s *****
```

> Nice catch! Long answer incoming slightly_smiling_face

Thank you for the explanation. The reason I'm asking is that I can't try to flash every build to verify that it works. I cannot risk having my daily driver be unbootable if for example the certificates don't match. Would be a pain to set it up again. Do you know if you can still switch to the other slot and boot it successfully, even if there are for example vbmeta or certificate issues? That would make it less risky. Unless of course rollback protection kicked in for whatever reason, but then there is a much bigger problem for all of us.

> * `META-INF/com/android/otacert`: I'm not sure why this would've changed. It should be an exact copy of your OTA signing certificate. Could you run it through `diff`?

I must have misread the output, because this run it matched as expected. Proves again that we humans are terrible observers.

**Comment by chenxiaolong** [comment]
> ```
> ***** Signing OTA zip *****
> Signing attempt 0
> - Compute placeholder property files: 0.0s
> - Replace metadata files in zip: 43.7s
> - Sign zip with signapk: 40.7s
> - Compute final property files: 0.0s
> Signing attempt 1
> - Compute placeholder property files: 0.0s
> - Replace metadata files in zip: 34.0s
> - Sign zip with signapk: 33.2s
> - Compute final property files: 0.0s
> - Validate file offsets and sizes: 0.0s
> ***** Completed after 240.6s *****
> ```

Thanks, that's helpful. So every full rewrite of the zip takes approximately the same amount of time.

I've just finished looking over how signapk works and it's nowhere near as complicated as I originally thought. I might be able implement avbroot in a single-pass way where the output zip is only written once. It might actually end up simplifying the code since a decent amount of complexity comes from dealing with file order and multiple passes.

> Thank you for the explanation. The reason I'm asking is that I can't try to flash every build to verify that it works. I cannot risk having my daily driver be unbootable if for example the certificates don't match. Would be a pain to set it up again.

Yeah, that's completely understandable. No problem at all!

(I do personally test flashing twice on my daily driver for every commit. Once to make sure it's bootable and a second time to ensure that the certificate validation will accept further OTAs.)

> Do you know if you can still switch to the other slot and boot it successfully, even if there are for example vbmeta or certificate issues? That would make it less risky. Unless of course rollback protection kicked in for whatever reason, but then there is a much bigger problem for all of us.

If there are vbmeta issues that render the device unbootable, the bootloader will flip back to the previous slot after a certain number of failed boot attempts. I've relied on this a couple times in the past. The bootloader only considers a slot "usable" once a userspace component starts and tells the bootloader that the slot is functional.

If the new slot bootable, I believe it's still possible to switch slots by running the AOSP `bootctl` tool as root, but that needs to be compiled from source. I haven't personally tested this, but will at some point.

> Proves again that we humans are terrible observers.

Agreed :smile:

**Comment by chenxiaolong** [comment]
As of commit a6f05145cd1af7bc74b994f914491387ddc507e6, avbroot now completely does zip signing itself. The output zip is created in a single-pass. The only temporary space needed is for boot image patching. It should be very significantly faster (~27.8 seconds on my machine).

Also added commit 44ef00b8d1d56ed86090c67a43bf63e7497d142c, which fixes the last bit-for-bit reproducibility issue I'm aware of. In the past, certain protobuf structures would sometimes be ordered differently in memory (about 1 in every 10 patching runs on my system), causing file checksums to change when serialized to files.

Did quite a bit of testing on this one. Patching on Fedora 37, Ubuntu 22.04, Ubuntu 22.10, Arch Linux, and Alpine 3.17 all produce bit-for-bit identical files. Alpine now works now that signapk has been removed. Despite it being written in Java, it had a dependency on the conscrypt native library, which only worked on glibc-based Linux distros. Tested flashing the patched file 4 times on my device (to verify both A -> B and B -> A work).

**Comment by pascallj** [comment]
This is a great optimization! Now done in 116.1s and less dependencies. Tested and works on Pixel 6a Bluejay.

**Pull request merged**
